services:
  postgres:
    image: postgres:16
    container_name: external-ombudsman-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - external_ombudsman_data:/var/lib/postgresql/data

volumes:
  external_ombudsman_data: